import pandas as pd


class Regions(object):
    def region_mapping():
        data = [
            ['Central', 'Attard'],
            ['Central', 'Balzan'],
            ['Central', 'Birkirkara'],
            ['Central', 'Fleur De Lys'],
            ['Central', 'Fort Cambridge'],
            ['Central', 'Guardamangia'],
            ['Central', 'Gzira'],
            ['Central', 'Iklin'],
            ['Central', 'Kappara'],
            ['Central', 'Lija'],
            ['Central', 'Mensija'],
            ['Central', 'Mriehel'],
            ['Central', 'Msida University Heights'],
            ['Central', 'Msida'],
            ['Central', 'Paceville'],
            ['Central', 'Pender Place'],
            ['Central', 'Pieta'],
            ['Central', 'Portomaso'],
            ['Central', 'San Gwann'],
            ['Central', 'Santa Venera'],
            ['Central', 'Sliema'],
            ['Central', 'St Julian\'s'],
            ['Central', 'Swatar'],
            ['Central', 'Ta\' Giorni'],
            ['Central', 'Ta\' Paris'],
            ['Central', 'Ta\' Xbiex'],
            ['Central', 'Tigne Point'],
            ['Gozo', 'Gozo - Fontana'],
            ['Gozo', 'Gozo - Fort Chambray'],
            ['Gozo', 'Gozo - Ghajnsielem'],
            ['Gozo', 'Gozo - Gharb'],
            ['Gozo', 'Gozo - Ghasri'],
            ['Gozo', 'Gozo - Kercem'],
            ['Gozo', 'Gozo - Marsalforn'],
            ['Gozo', 'Gozo - Mgarr'],
            ['Gozo', 'Gozo - Munxar'],
            ['Gozo', 'Gozo - Nadur'],
            ['Gozo', 'Gozo - Qala'],
            ['Gozo', 'Gozo - Rabat'],
            ['Gozo', 'Gozo - San Lawrenz'],
            ['Gozo', 'Gozo - Sannat'],
            ['Gozo', 'Gozo - Santa Lucija'],
            ['Gozo', 'Gozo - Victoria'],
            ['Gozo', 'Gozo - Xaghra'],
            ['Gozo', 'Gozo - Xewkija'],
            ['Gozo', 'Gozo - Xlendi'],
            ['Gozo', 'Gozo - Zebbug'],
            ['Northern', 'Bahar Ic-Caghaq'],
            ['Northern', 'Bahrija'],
            ['Northern', 'Bidnija'],
            ['Northern', 'Bingemma'],
            ['Northern', 'Birguma'],
            ['Northern', 'Bugibba'],
            ['Northern', 'Burmarrad'],
            ['Northern', 'Buskett'],
            ['Northern', 'Dingli'],
            ['Northern', 'Ghajn Tuffieha'],
            ['Northern', 'Gharghur'],
            ['Northern', 'High Ridge'],
            ['Northern', 'Madliena'],
            ['Northern', 'Manikata'],
            ['Northern', 'Manikata'],
            ['Northern', 'Mdina'],
            ['Northern', 'Mellieha'],
            ['Northern', 'Mgarr'],
            ['Northern', 'Mosta'],
            ['Northern', 'Mtahleb'],
            ['Northern', 'Mtarfa'],
            ['Northern', 'Naxxar'],
            ['Northern', 'Pembroke'],
            ['Northern', 'Qawra'],
            ['Northern', 'Rabat'],
            ['Northern', 'Salina'],
            ['Northern', 'San Pawl tat Targa'],
            ['Northern', 'Santa Maria Estate'],
            ['Northern', 'St Paul\'s Bay'],
            ['Northern', 'Swieqi'],
            ['Northern', 'Ta\' Qali'],
            ['Northern', 'Ta\' l-Ibragg'],
            ['Northern', 'The Village'],
            ['Northern', 'Victoria Gardens'],
            ['Northern', 'Wardija'],
            ['Northern', 'Xemxija'],
            ['Northern', 'Zebbiegh'],
            ['South Eastern', 'Birgu'],
            ['South Eastern', 'Bormla'],
            ['South Eastern', 'Cospicua'],
            ['South Eastern', 'Fgura'],
            ['South Eastern', 'Floriana'],
            ['South Eastern', 'Kalkara'],
            ['South Eastern', 'Marsa'],
            ['South Eastern', 'Marsascala'],
            ['South Eastern', 'Marsaskala'],
            ['South Eastern', 'Marsaxlokk'],
            ['South Eastern', 'Paola'],
            ['South Eastern', 'Santa Lucia'],
            ['South Eastern', 'Senglea'],
            ['South Eastern', 'Ta Monita Residence'],
            ['South Eastern', 'Tarxien'],
            ['South Eastern', 'The Shoreline'],
            ['South Eastern', 'Valletta'],
            ['South Eastern', 'Vittoriosa'],
            ['South Eastern', 'Xghajra'],
            ['South Eastern', 'Zabbar'],
            ['South Eastern', 'Zejtun'],
            ['Southern', 'Birzebbuga'],
            ['Southern', 'Blata l\' Bajda'],
            ['Southern', 'Ghaxaq'],
            ['Southern', 'Gudja'],
            ['Southern', 'Hal-Far'],
            ['Southern', 'Hamrun'],
            ['Southern', 'Handaq'],
            ['Southern', 'Kirkop'],
            ['Southern', 'Luqa'],
            ['Southern', 'Mqabba'],
            ['Southern', 'Qormi'],
            ['Southern', 'Qrendi'],
            ['Southern', 'Safi'],
            ['Southern', 'Santa Lucija'],
            ['Southern', 'Siggiewi'],
            ['Southern', 'Zebbug'],
            ['Southern', 'Zurrieq']
        ]

        return pd.DataFrame(data, columns=['Province', 'Town'])
