import pandas as pd


class Configuration(object):
    def exclude_types() -> list:
        return [
            'Basement Garage',
            'Boutique Hotel',
            'Business Concern',
            'Catering Establishments',
            'Comm. (2C Education)',
            'Comm. (4A Financial, Professional & Other Offices)',
            'Comm. (4B Retail)',
            'Comm. (4D Food & Drink Cooking)',
            'Commercial Class 4',
            'Commercial Class 5',
            'Commercial Class 6',
            'Commercial Shop',
            'Commercial',
            'Food & Drink (Cooking Allowed) Class 4D',
            'Garage (Commercial)',
            'Garage (Residential)',
            'Garage (Street Level)',
            'Garage Residential',
            'Garage Space',
            'Garage',
            'Guest House - Hotel',
            'Hotel',
            'Hotels',
            'Office Block',
            'Office Space',
            'Offices Class 4A',
            'Offices',
            'Residential Garage',
            'Restaurant',
            'Retail Class 4B',
            'Retail Outlet',
            'Semi Basement Garage',
            'Shop',
            'Showroom',
            'Street Level Garage',
            'Warehouse',
            'Within Development Zone (DZ)',
        ]

    def exclude_towns() -> list:
        return [
            'Caribbean',
            'Cottonera',
            'Migration Locality Catch All',
            'Raguza',
            'Sicily, Ragusa',
            'Sicily, Toarmina',
            'St. Lucia',
            'Tuscany',
        ]

    def mapping_types() -> dict:
        data = [
            ['Airspace', 'Airspace (Residential)'],
            ['Apartment', 'Flats'],
            ['Apartment', 'Apartment (Studio)'],
            ['Apartment', 'Second Floor Apartment'],
            ['Apartment', 'Apartment (Flatlet)'],
            ['Apartment', 'Apartment (Top Floor)'],
            ['Apartment', 'Fourth Floor Apartment'],
            ['Apartment', 'FlatLet'],
            ['Apartment', 'Fifth Floor Apartment'],
            ['Apartment', 'Apartment (Block)'],
            ['Apartment', 'Ground Floor Apartment'],
            ['Apartment', 'Third Floor Apartment'],
            ['Apartment', 'Elev. Ground Floor Apartment'],
            ['Apartment', 'Studio Flat'],
            ['Apartment', 'Studio Apartment'],
            ['Apartment', 'First Floor Apartment'],
            ['Apartment', 'Apartment with airspace'],
            ['Apartment', 'Corner Apartment'],
            ['Apartment', 'Semi Basement Apartment'],
            ['Apartment Duplex', 'Duplex Apartment'],
            ['Apartment Duplex', 'Apartment (Duplex)'],
            ['Block of Apartments', 'Apartment Block'],
            ['Block of Apartments', 'Block of Apartments (Res)'],
            ['Block of Apartments', 'Block of Flats'],
            ['Block of Apartments', 'Block of Mixed Units'],
            ['Bungalow', 'Bungalow Detached'],
            ['Bungalow', 'Bungalow Fully-Detached'],
            ['Bungalow', 'Detached Bungalow'],
            ['Bungalow', 'Fully Detached Bungalow'],
            ['Bungalow', 'Terraced Bungalow'],
            ['Bungalow Semi-Detached', 'Semi-detached Bungalow'],
            ['Bungalow Semi-Detached', 'Semi-Det Bungalow'],
            ['Bungalow Semi-Detached', 'Semi Detached Bungalow'],
            ['Farmhouse', 'Converted Farmhouse'],
            ['Farmhouse Unconverted', 'Unconverted Farmhouse'],
            ['Guesthouse', 'Guest House'],
            ['Guesthouse', 'Guesthouses'],
            ['House of Character', 'Converted House of Character'],
            ['House of Character Semi-Converted', 'Semi Converted House of Character'],
            ['House of Character Unconverted', 'Unconverted House of Character'],
            ['Maisonette', 'Ground Floor Maisonette'],
            ['Maisonette', 'Maisonette (Ground Floor)'],
            ['Maisonette', 'First Floor Maisonette'],
            ['Maisonette', 'Elevated Ground Floor Maisonette'],
            ['Maisonette', 'Maisonette (1st Floor)'],
            ['Maisonette', 'Maisonette (Elevated ground floor)'],
            ['Maisonette', 'First Floor (+) Maisonette'],
            ['Maisonette', 'Solitary Maisonette'],
            ['Maisonette', 'Second Floor Maisonette'],
            ['Maisonette', '1st Floor Maisonette'],
            ['Maisonette', 'Maisonette (Semi-basement)'],
            ['Maisonette', '2nd Floor maisonette'],
            ['Maisonette', 'Maisonette (Loft)'],
            ['Maisonette', 'Maisonette (Solitary)'],
            ['Maisonette', 'Gr Floor Maisonette'],
            ['Maisonette', 'Maisonette Solitary'],
            ['Maisonette', 'Semi Basement Maisonette'],
            ['Maisonette', 'Maisonette (2nd Floor)'],
            ['Maisonette', 'Private Maisonette'],
            ['Maisonette', 'Semi-basement Maisonette'],
            ['Maisonette Duplex', 'Duplex Maisonette'],
            ['Maisonette Duplex', 'Maisonette (Duplex)'],
            ['Maisonette Duplex', 'Maisonette Solitary Duplex'],
            ['Maisonette Duplex', 'Solitary Duplex Maisonette'],
            ['Maisonette Semi-Detached', 'Maisonette (Semi-detached)'],
            ['Maisonette Semi-Detached', 'Semi Detached Maisonette'],
            ['Maisonette Triplex', 'Triplex Maisonette'],
            ['Palazzino', 'Palazzo / Palazzino'],
            ['Palazzo Unconverted', 'Unconverted Palazzo'],
            ['Penthouse', 'Corner Penthouse'],
            ['Penthouse', 'Fully Detached Penthouse'],
            ['Penthouse', 'Studio Penthouse'],
            ['Penthouse Duplex', 'Duplex Penthouse'],
            ['Penthouse Semi-Detached', 'Semi Detached Penthouse'],
            ['Plot', 'Plot (Residential)'],
            ['Plot with Permit', 'Plot Within Building Scheme'],
            ['Plot with Permit', 'Development'],
            ['Room', 'Hostels'],
            ['Room', 'Shared Accommodation'],
            ['Site', 'Site (Residential)'],
            ['Site', 'Field'],
            ['Townhouse', 'Town House'],
            ['Townhouse', 'Converted Town House'],
            ['Townhouse Semi-Converted', 'Semi Converted Townhouse'],
            ['Townhouse Unconverted', 'Unconverted Town House'],
            ['Villa', 'Villa Detached'],
            ['Villa', 'Fully-detached Villa'],
            ['Villa', 'Detached Villa'],
            ['Villa', 'Villa Fully-Detached'],
            ['Villa', 'Fully Detached Villa'],
            ['Villa', 'Terraced Villa'],
            ['Villa Semi-Detached', 'Semi-Detached Villa'],
            ['Villa Semi-Detached', 'Semi Detached Villa'],
            ['Villa Semi-Detached', 'Semi-detached Villa'],
        ]

        mapping_types = pd.DataFrame(data, columns=['Standard', 'Variant'])
        mapping_types = {row['Variant']: row['Standard'] for _, row in mapping_types.iterrows()}

        return mapping_types

    @staticmethod
    def mapping_towns() -> dict:
        data = [
            ['Bahar Ic-Caghaq', 'Bahar Ic Caghaq'],
            ['Bahar Ic-Caghaq', 'Bahar ic-Caghaq'],
            ['Birgu', 'Birgu Vittoriosa'],
            ['Birgu', 'St. Angelo Mansions'],
            ['Birgu', 'Vittoriosa (Birgu)'],
            ['Birgu', 'Vittoriosa'],
            ['Birgu', 'Vittoriosa, St Angelo Mansions'],
            ['Birkirkara', 'B\'Kara'],
            ['Birkirkara', 'Central Business District'],
            ['Birkirkara', 'Fleur De Lys'],
            ['Birkirkara', 'Fleur de Lys'],
            ['Birkirkara', 'Fleur-De-Lys'],
            ['Birkirkara', 'Fleur-de-Lys'],
            ['Birkirkara', 'Ta\' Paris Birkirkara'],
            ['Birkirkara', 'Ta\' Paris'],
            ['Birzebbuga', 'Benghajsa'],
            ['Birzebbuga', 'Birzebbugia'],
            ['Birzebbuga', 'Qajjenza Birzebbuga'],
            ['Birzebbuga', 'Qajjenza'],
            ['Blata Il-Bajda', 'Blata L-Bajda'],
            ['Blata Il-Bajda', 'Blata l\' Bajda'],
            ['Blata Il-Bajda', 'Blata l\'Bajda'],
            ['Bugibba', 'B\'Bugia'],
            ['Cospicua', 'Bormla Cospicua'],
            ['Cospicua', 'Cospicua (Bormla)'],
            ['Gharghur', 'Hal Gharghur'],
            ['Gozo - Fontana', 'Fontana'],
            ['Gozo - Fontana', 'Gozo Fontana'],
            ['Gozo - Ghajnsielem', 'Fort Chambray'],
            ['Gozo - Ghajnsielem', 'Ghajnsielem'],
            ['Gozo - Ghajnsielem', 'Gozo - Fort Chambray'],
            ['Gozo - Ghajnsielem', 'Gozo Ghajnsielem'],
            ['Gozo - Gharb', 'Gharb'],
            ['Gozo - Gharb', 'Gozo Gharb'],
            ['Gozo - Gharb', 'Gozo L-Gharb'],
            ['Gozo - Ghasri', 'Ghasri'],
            ['Gozo - Ghasri', 'Gozo Ghasri'],
            ['Gozo - Ghasri', 'Gozo L-Ghasri'],
            ['Gozo - Kercem', 'Gozo - Santa Lucija'],
            ['Gozo - Kercem', 'Gozo Kercem'],
            ['Gozo - Kercem', 'Kercem'],
            ['Gozo - Kercem', 'Santa Lucia'],
            ['Gozo - Kercem', 'Santa Lucija (Gozo)'],
            ['Gozo - Marsalforn', 'Gozo Marsalforn'],
            ['Gozo - Marsalforn', 'Marsalforn'],
            ['Gozo - Mgarr', 'Mgarr (Gozo)'],
            ['Gozo - Munxar', 'Gozo Il-Munxar'],
            ['Gozo - Munxar', 'Munxar'],
            ['Gozo - Nadur', 'Gozo In-Nadur'],
            ['Gozo - Nadur', 'Nadur'],
            ['Gozo - Qala', 'Gozo Il-Qala'],
            ['Gozo - Qala', 'Gozo Qala'],
            ['Gozo - Qala', 'Qala'],
            ['Gozo - San Lawrenz', 'Gozo San Lawrenz'],
            ['Gozo - San Lawrenz', 'Kempinski'],
            ['Gozo - San Lawrenz', 'San Lawrenz'],
            ['Gozo - Sannat', 'Gozo Sannat'],
            ['Gozo - Sannat', 'Sannat'],
            ['Gozo - Victoria', 'Gozo - Rabat'],
            ['Gozo - Victoria', 'Gozo Ir-Rabat'],
            ['Gozo - Victoria', 'Gozo Victoria Rabat'],
            ['Gozo - Victoria', 'Rabat, Gozo'],
            ['Gozo - Victoria', 'Victoria'],
            ['Gozo - Xaghra', 'Gozo Xaghra'],
            ['Gozo - Xaghra', 'Xaghra (Gozo)'],
            ['Gozo - Xaghra', 'Xaghra'],
            ['Gozo - Xewkija', 'Gozo Ix-Xewkija'],
            ['Gozo - Xewkija', 'Xewkija'],
            ['Gozo - Xlendi', 'Gozo Xlendi'],
            ['Gozo - Xlendi', 'St Andrew\'s'],
            ['Gozo - Xlendi', 'Xlendi'],
            ['Gozo - Zebbug', 'Gozo Iz-Zebbug'],
            ['Gozo - Zebbug', 'Zebbug (Gozo)'],
            ['Iklin', 'L-Iklin'],
            ['Iklin', 'L\'Iklin'],
            ['Kalkara', 'Kalkara, Shoreline'],
            ['Kalkara', 'Kalkara, Smart City'],
            ['Kalkara', 'The Shoreline at Smart City'],
            ['Kalkara', 'The Shoreline'],
            ['Luqa', 'Hal Farrug Luqa'],
            ['Luqa', 'Hal Farrug'],
            ['Manikata', 'Ghajn Tuffieha'],
            ['Marsaskala', 'M\'Scala'],
            ['Marsaskala', 'Marsascala'],
            ['Marsaskala', 'Marsascala, Ta\' Monita Residence'],
            ['Marsaskala', 'Ta Monita Residence'],
            ['Marsaskala', 'Ta Monita'],
            ['Marsaskala', 'Taâ€™ Monita Residence M\'Skala'],
            ['Marsaskala', 'Ta’ Monita Residence M\'Skala'],
            ['Marsaxlokk', 'Dellimara'],
            ['Marsaxlokk', 'M\'Xlokk'],
            ['Mellieha', 'Ghadira'],
            ['Mellieha', 'Mellieha, Ghadira'],
            ['Mellieha', 'Mellieha, Santa Maria Estate'],
            ['Mellieha', 'Mellieha, Tas-Sellum'],
            ['Mellieha', 'Santa Maria Estate Mellieha'],
            ['Mellieha', 'Santa Maria Estate'],
            ['Mellieha', 'Selmun'],
            ['Mellieha', 'Southridge'],
            ['Mellieha', 'Tas Sellum'],
            ['Mgarr', 'Bingemma'],
            ['Mgarr', 'Zebbiegh'],
            ['Msida', 'Msida University Heights'],
            ['Naxxar', 'Birguma'],
            ['Naxxar', 'Maghtab Naxxar'],
            ['Naxxar', 'San Pawl Tat-Targa'],
            ['Naxxar', 'San Pawl tat Targa'],
            ['Naxxar', 'San Pawl tat-Targa Naxxar'],
            ['Naxxar', 'San Pawl tat-Targa'],
            ['Naxxar', 'The Village'],
            ['Paola', 'Il-Kortin'],
            ['Paola', 'Paola Rahal Gdid'],
            ['Pembroke', 'St Andrews'],
            ['Pieta', 'G\'Mangia'],
            ['Pieta', 'Guardamangia'],
            ['Pieta', 'Gwardamanga'],
            ['Pieta', 'Gwardamangia'],
            ['Qormi', 'Handaq Qormi'],
            ['Qormi', 'Handaq'],
            ['Rabat', 'Mtahleb Rabat'],
            ['Rabat', 'Mtahleb'],
            ['Rabat', 'Rabat, Tal-Virtu'],
            ['Saint Julian\'s', 'Mercury Towers'],
            ['Saint Julian\'s', 'Pender Gardens St Julians'],
            ['Saint Julian\'s', 'Pender Gardens'],
            ['Saint Julian\'s', 'Portomaso Laguna'],
            ['Saint Julian\'s', 'Portomaso'],
            ['Saint Julian\'s', 'Sliema, Fort Cambridge'],
            ['Saint Julian\'s', 'Sliema, Tigne Point'],
            ['Saint Julian\'s', 'Sliema, Tigne'],
            ['Saint Julian\'s', 'St Julian\'s San Giljan'],
            ['Saint Julian\'s', 'St Julian\'s'],
            ['Saint Julian\'s', 'St Julians'],
            ['Saint Julian\'s', 'St Julians, Mercury House'],
            ['Saint Julian\'s', 'St Julians, Pender Gardens'],
            ['Saint Julian\'s', 'St Julians, St George\'S Park'],
            ['Saint Julian\'s', 'St Julians, The Gardens'],
            ['Saint Julian\'s', 'St. Julians'],
            ['Saint Julian\'s', 'St. Julians, Paceville'],
            ['Saint Julian\'s', 'St. Julians, Portomaso'],
            ['Saint Julian\'s', 'St. Julians, Ta\' Giorni'],
            ['Saint Julian\'s', 'St.Julians'],
            ['Saint Julian\'s', 'Ta Giorni'],
            ['Saint Julian\'s', 'Ta\' Giorni St Julians'],
            ['Saint Julian\'s', 'Ta\' Giorni'],
            ['Saint Julian\'s', 'The Gardens'],
            ['Saint Paul\'s Bay', 'Pender Place'],
            ['Saint Paul\'s Bay', 'Pwales'],
            ['Saint Paul\'s Bay', 'St Paul\'s Bay San Pawl il-Bahar'],
            ['Saint Paul\'s Bay', 'St Paul\'s Bay'],
            ['Saint Paul\'s Bay', 'St Pauls Bay'],
            ['Saint Paul\'s Bay', 'St. Pauls Bay'],
            ['Saint Paul\'s Bay', 'St.Pauls Bay'],
            ['San Gwann', 'Mensija San Gwann'],
            ['San Gwann', 'Mensija'],
            ['San Gwann', 'Monterosa Gardens'],
            ['San Gwann', 'Ta\' Zwejt'],
            ['Santa Venera', 'St.Venera'],
            ['Senglea', 'Senglea (L-Isla)'],
            ['Senglea', 'Senglea Isla'],
            ['Siggiewi', 'Buskett'],
            ['Sliema', 'Fort Cambridge'],
            ['Sliema', 'Tigne Point'],
            ['Swatar', 'Swatar Birkirkara'],
            ['Swieqi', 'High Ridge'],
            ['Swieqi', 'Ibrag'],
            ['Swieqi', 'Ibrag, High Ridge'],
            ['Swieqi', 'Ibrag, Victoria Gardens'],
            ['Swieqi', 'Ibragg'],
            ['Swieqi', 'Madliena Village'],
            ['Swieqi', 'Madliena, Madliena Village'],
            ['Swieqi', 'Swieqi, St Andrews'],
            ['Swieqi', 'Ta\' l-Ibragg'],
            ['Swieqi', 'Ta\'L-ibrag'],
            ['Swieqi', 'Tal-Ibrag'],
            ['Swieqi', 'Victoria Gardens Ibrag'],
            ['Swieqi', 'Victoria Gardens'],
            ['Ta\' Xbiex', 'Ta\'Xbiex'],
            ['Zabbar', 'Haz-Zabbar'],
            ['Zebbug', 'Iz-Zebbug'],
            ['Zejtun', 'Bir id-deheb'],
            ['Zurrieq', 'Zurrieq Bubaqra'],
        ]

        mapping_towns = pd.DataFrame(data, columns=['Standard', 'Variant'])
        mapping_towns = {row['Variant']: row['Standard'] for _, row in mapping_towns.iterrows()}

        return mapping_towns

    @staticmethod
    def imply_province() -> pd.DataFrame:
        data = [
            ['Central', 'Attard'],
            ['Central', 'Balzan'],
            ['Central', 'Birkirkara'],
            ['Central', 'Blata Il-Bajda'],
            ['Central', 'Hamrun'],
            ['Central', 'Iklin'],
            ['Central', 'Lija'],
            ['Central', 'Mosta'],
            ['Central', 'Mriehel'],
            ['Central', 'Naxxar'],
            ['Central', 'Qormi'],
            ['Central', 'Santa Venera'],
            ['Central', 'Swatar'],
            ['East', 'Bahar Ic-Caghaq'],
            ['East', 'Floriana'],
            ['East', 'Gharghur'],
            ['East', 'Gzira'],
            ['East', 'Kappara'],
            ['East', 'Madliena'],
            ['East', 'Maghtab'],
            ['East', 'Msida'],
            ['East', 'Paceville'],
            ['East', 'Pembroke'],
            ['East', 'Pieta'],
            ['East', 'Saint Julian\'s'],
            ['East', 'San Gwann'],
            ['East', 'Sliema'],
            ['East', 'Swieqi'],
            ['East', 'Ta\' Xbiex'],
            ['East', 'Valletta'],
            ['Gozo', 'Gozo - Citadel'],
            ['Gozo', 'Gozo - Fontana'],
            ['Gozo', 'Gozo - Ghajnsielem'],
            ['Gozo', 'Gozo - Gharb'],
            ['Gozo', 'Gozo - Ghasri'],
            ['Gozo', 'Gozo - Kercem'],
            ['Gozo', 'Gozo - Marsalforn'],
            ['Gozo', 'Gozo - Mdina'],
            ['Gozo', 'Gozo - Mgarr'],
            ['Gozo', 'Gozo - Munxar'],
            ['Gozo', 'Gozo - Nadur'],
            ['Gozo', 'Gozo - Qala'],
            ['Gozo', 'Gozo - San Lawrenz'],
            ['Gozo', 'Gozo - Sannat'],
            ['Gozo', 'Gozo - Victoria'],
            ['Gozo', 'Gozo - Xaghra'],
            ['Gozo', 'Gozo - Xewkija'],
            ['Gozo', 'Gozo - Xlendi'],
            ['Gozo', 'Gozo - Zebbug'],
            ['North', 'Bidnija'],
            ['North', 'Bugibba'],
            ['North', 'Burmarrad'],
            ['North', 'Manikata'],
            ['North', 'Mellieha'],
            ['North', 'Mgarr'],
            ['North', 'Qawra'],
            ['North', 'Saint Paul\'s Bay'],
            ['North', 'Salina'],
            ['North', 'Wardija'],
            ['North', 'Xemxija'],
            ['South', 'Birgu'],
            ['South', 'Birzebbuga'],
            ['South', 'Cospicua'],
            ['South', 'Fgura'],
            ['South', 'Ghaxaq'],
            ['South', 'Gudja'],
            ['South', 'Hal Far'],
            ['South', 'Kalkara'],
            ['South', 'Kirkop'],
            ['South', 'Luqa'],
            ['South', 'Marsa'],
            ['South', 'Marsaskala'],
            ['South', 'Marsaxlokk'],
            ['South', 'Mqabba'],
            ['South', 'Paola'],
            ['South', 'Qrendi'],
            ['South', 'Safi'],
            ['South', 'Santa Lucija'],
            ['South', 'Senglea'],
            ['South', 'Tarxien'],
            ['South', 'Xghajra'],
            ['South', 'Zabbar'],
            ['South', 'Zejtun'],
            ['South', 'Zurrieq'],
            ['West', 'Bahrija'],
            ['West', 'Dingli'],
            ['West', 'Mdina'],
            ['West', 'Mtarfa'],
            ['West', 'Rabat'],
            ['West', 'Siggiewi'],
            ['West', 'Zebbug']
        ]

        return pd.DataFrame(data, columns=['Province', 'Town'])
