import pandas as pd


class Configuration(object):
    def stage_plan() -> list:
        return [
            'being built',
            'development',
            'on plan',
        ]

    def stage_shell() -> list:
        return [
            'ready built',
            'shell',
        ]

    def stage_finished() -> list:
        return [
            'finished',
            'finsished',
        ]

    def stage_furnished() -> list:
        return [
            'converted',
            'furnished',
            'well-kept',
            'fully',
        ]

    def stage_unconverted() -> list:
        return [
            'done up',
            'needs modernizing',
            'renovated',
            'unconverted',
        ]

    def exclude_types() -> list:
        return [
            'Boutique Hotel',
            'Commercial Class 4',
            'Commercial Shop',
            'Commercial',
            'Guesthouses',
            'Guest House - Hotel',
            'Guest House',
            'Offices',
            'Warehouse',
            'Within Development Zone (DZ)',
        ]

    def exclude_towns() -> list:
        return [
            'Gozo',
            'SDA',
            'Space',
            'St. Lucia',
            'Tuscany, Arezzo',
        ]

    def mapping_stages() -> dict:
        data = [
            ['Finished', 'Partly Furnished'],
            ['Finished', 'Unconverted'],
            ['Finished', 'Unfurnished'],
            ['Unclassified', 'NA (Commercial, Garage, Site, Plot)'],
        ]

        return pd.DataFrame(data, columns=['Standard', 'Variant'])

    def mapping_types() -> dict:
        data = [
            ['Agriculture Land', 'Land'],
            ['Airspace', 'Airspace (Residential)'],
            ['Apartment Duplex', 'Apartment (Duplex)'],
            ['Apartment Duplex', 'Duplex Apartment'],
            ['Apartment', 'Apartment (Apartment)'],
            ['Apartment', 'Apartment (Flatlet)'],
            ['Apartment', 'Apartment (Studio)'],
            ['Apartment', 'Apartment (Top Floor)'],
            ['Apartment', 'Apartments'],
            ['Apartment', 'Block Of Mixed Units'],
            ['Apartment', 'Boat'],
            ['Apartment', 'Boathouses'],
            ['Apartment', 'Corner Apartment'],
            ['Apartment', 'Elev. Ground Floor Apartment'],
            ['Apartment', 'Fifth Floor Apartment'],
            ['Apartment', 'First Floor Apartment'],
            ['Apartment', 'FlatLet'],
            ['Apartment', 'Flats'],
            ['Apartment', 'Fourth Floor Apartment'],
            ['Apartment', 'Ground Floor Apartment'],
            ['Apartment', 'Second Floor Apartment'],
            ['Apartment', 'Semi Basement Apartment'],
            ['Apartment', 'Studio Apartment'],
            ['Apartment', 'Studio Apartments'],
            ['Apartment', 'Studio Flat'],
            ['Apartment', 'Third Floor Apartment'],
            ['Block of Apartment', 'Apartment Block'],
            ['Block of Apartment', 'Block Of Apartments'],
            ['Block of Apartment', 'Block of Apartment (Res)'],
            ['Block of Apartment', 'Block of Apartments (Res)'],
            ['Block of Apartment', 'Block of Flats'],
            ['Block of Apartment', 'Block'],
            ['Bungalow Semi-Detached', 'Bungalow Semi'],
            ['Bungalow Semi-Detached', 'Semi-detached Bungalow'],
            ['Bungalow', 'Bungalow Detached'],
            ['Bungalow', 'Bungalow Fully-Detached'],
            ['Bungalow', 'Bungalows'],
            ['Bungalow', 'Detached Bungalow'],
            ['Bungalow', 'Fully Detached Bungalow'],
            ['Farmhouse', 'Converted Farmhouse'],
            ['Farmhouse', 'Cottage'],
            ['Farmhouse', 'Farmhouses'],
            ['Garage', 'Garage (Residential)'],
            ['Garage', 'Garage Residential'],
            ['Garage', 'Garage Space'],
            ['Garage', 'Garage/Parking Space'],
            ['House of Character Unconverted', 'Unconverted House Of Character'],
            ['House of Character Unconverted', 'Unconverted House of Character'],
            ['House of Character', 'Converted House Of Character'],
            ['House of Character', 'Converted House of Character'],
            ['House of Character', 'House Of Character'],
            ['Maisonette Duplex', 'Duplex Maisonette'],
            ['Maisonette Duplex', 'Maisonette (Duplex)'],
            ['Maisonette Duplex', 'Maisonette Solitary Duplex'],
            ['Maisonette Duplex', 'Solitary Duplex Maisonette'],
            ['Maisonette Semi-Detached', 'Maisonette Semi'],
            ['Maisonette Semi-Detached', 'Semi Detached Maisonette'],
            ['Maisonette', '1st Floor Maisonette'],
            ['Maisonette', '2nd Floor maisonette'],
            ['Maisonette', 'Elevated Ground Floor Maisonette'],
            ['Maisonette', 'First Floor (+) Maisonette'],
            ['Maisonette', 'First Floor Maisonette'],
            ['Maisonette', 'Gr Floor Maisonette'],
            ['Maisonette', 'Ground Floor Maisonette'],
            ['Maisonette', 'Maisonette (1St Floor)'],
            ['Maisonette', 'Maisonette (2Nd Floor)'],
            ['Maisonette', 'Maisonette (Elevated Ground Floor)'],
            ['Maisonette', 'Maisonette (Ground Floor)'],
            ['Maisonette', 'Maisonette (Semi-Basement)'],
            ['Maisonette', 'Maisonette (Solitary)'],
            ['Maisonette', 'Maisonette Solitary'],
            ['Maisonette', 'Maisonettes'],
            ['Maisonette', 'Private Maisonette'],
            ['Maisonette', 'Second Floor Maisonette'],
            ['Maisonette', 'Semi Basement Maisonette'],
            ['Maisonette', 'Semi-basement Maisonette'],
            ['Maisonette', 'Solitary Maisonette'],
            ['Palazzo', 'Palace/Castle/Manor'],
            ['Palazzo', 'Palazzino'],
            ['Palazzo', 'Palazzo / Palazzino'],
            ['Penthouse Duplex', 'Duplex Penthouse'],
            ['Penthouse', 'Apartment With Airspace'],
            ['Penthouse', 'Corner Penthouse'],
            ['Penthouse', 'Penthouses'],
            ['Penthouse', 'Studio Penthouse'],
            ['Plot with Permit', 'Development'],
            ['Plot with Permit', 'Plot Within Building Scheme'],
            ['Plot', 'Site'],
            ['Room', 'Hostels'],
            ['Room', 'Rooms'],
            ['Room', 'Shared Accommodation'],
            ['Terraced House', 'Corner Terraced House'],
            ['Terraced House', 'Terraced Houses'],
            ['Townhouse Unconverted', 'Unconverted Town House'],
            ['Townhouse', 'Converted Town House'],
            ['Townhouse', 'Town House'],
            ['Townhouse', 'Townhouses'],
            ['Villa Semi-Detached', 'Semi Detached Villa'],
            ['Villa Semi-Detached', 'Semi-Detached Villa'],
            ['Villa Semi-Detached', 'Semi-detached Villa'],
            ['Villa Semi-Detached', 'Villa Semi'],
            ['Villa', 'Detached Villa'],
            ['Villa', 'Fully Detached Villa'],
            ['Villa', 'Fully-detached Villa'],
            ['Villa', 'Terraced Villa'],
            ['Villa', 'Villa Detached'],
            ['Villa', 'Villa Fully-Detached'],
        ]

        return pd.DataFrame(data, columns=['Standard', 'Variant'])

    @staticmethod
    def mapping_towns() -> dict:
        data = [
            ['Bahar Ic-Caghaq', 'Bahar Ic Caghaq'],
            ['Bahar Ic-Caghaq', 'Bahar ic-Caghaq'],
            ['Birgu', 'Birgu Vittoriosa'],
            ['Birgu', 'St. Angelo Mansions'],
            ['Birgu', 'Vittoriosa (Birgu)'],
            ['Birgu', 'Vittoriosa'],
            ['Birgu', 'Vittoriosa, St Angelo Mansions'],
            ['Birkirkara', 'B\'Kara'],
            ['Birkirkara', 'Fleur De Lys'],
            ['Birkirkara', 'Fleur-De-Lys'],
            ['Birkirkara', 'Fleur-de-Lys'],
            ['Birkirkara', 'Fleur-de-lys'],
            ['Birkirkara', 'Ta\' Paris Birkirkara'],
            ['Birkirkara', 'Ta\' Paris'],
            ['Birzebbuga', 'Benghajsa'],
            ['Birzebbuga', 'Birzebbugia'],
            ['Birzebbuga', 'Qajjenza'],
            ['Blata Il-Bajda', 'Blata L-Bajda'],
            ['Blata Il-Bajda', 'Blata L\'Bajda'],
            ['Blata Il-Bajda', 'Blata l-Bajda'],
            ['Blata Il-Bajda', 'Blata l\' Bajda'],
            ['Blata Il-Bajda', 'Blata l\'Bajda'],
            ['Bugibba', 'B\'Bugia'],
            ['Cospicua', 'Bormla Cospicua'],
            ['Cospicua', 'Bormla'],
            ['Cospicua', 'Cospicua (Bormla)'],
            ['Gozo - Fontana', 'Fontana'],
            ['Gozo - Fontana', 'Gozo Fontana'],
            ['Gozo - Ghajnsielem', 'Fort Chambray'],
            ['Gozo - Ghajnsielem', 'Ghajnsielem'],
            ['Gozo - Ghajnsielem', 'Gozo - Fort Chambray'],
            ['Gozo - Ghajnsielem', 'Gozo Ghajnsielem'],
            ['Gozo - Gharb', 'Gharb'],
            ['Gozo - Gharb', 'Gozo Gharb'],
            ['Gozo - Gharb', 'Gozo L-Gharb'],
            ['Gozo - Ghasri', 'Ghasri'],
            ['Gozo - Ghasri', 'Gozo Ghasri'],
            ['Gozo - Ghasri', 'Gozo L-Ghasri'],
            ['Gozo - Kercem', 'Gozo - Santa Lucija'],
            ['Gozo - Kercem', 'Gozo Kercem'],
            ['Gozo - Kercem', 'Kercem'],
            ['Gozo - Kercem', 'Santa Lucija (Gozo)'],
            ['Gozo - Marsalforn', 'GOZO Marsalforn'],
            ['Gozo - Marsalforn', 'Gozo Marsalforn'],
            ['Gozo - Marsalforn', 'Marsalforn'],
            ['Gozo - Mgarr', 'Mgarr (Gozo)'],
            ['Gozo - Munxar', 'Gozo Il-Munxar'],
            ['Gozo - Munxar', 'Gozo Munxar'],
            ['Gozo - Munxar', 'Munxar'],
            ['Gozo - Nadur', 'Gozo In-Nadur'],
            ['Gozo - Nadur', 'Gozo Nadur'],
            ['Gozo - Nadur', 'Nadur'],
            ['Gozo - Qala', 'Gozo Il-Qala'],
            ['Gozo - Qala', 'Gozo Qala'],
            ['Gozo - Qala', 'Qala'],
            ['Gozo - San Lawrenz', 'Gozo San Lawrenz'],
            ['Gozo - San Lawrenz', 'San Lawrenz'],
            ['Gozo - Sannat', 'Gozo Sannat'],
            ['Gozo - Sannat', 'Sannat'],
            ['Gozo - Victoria', 'Gozo - Rabat'],
            ['Gozo - Victoria', 'Gozo Ir-Rabat'],
            ['Gozo - Victoria', 'Gozo Rabat (Victoria)'],
            ['Gozo - Victoria', 'Rabat, Gozo'],
            ['Gozo - Victoria', 'Victoria'],
            ['Gozo - Xaghra', 'Gozo Xaghra'],
            ['Gozo - Xaghra', 'Xaghra (Gozo)'],
            ['Gozo - Xaghra', 'Xaghra'],
            ['Gozo - Xewkija', 'Gozo Ix-Xewkija'],
            ['Gozo - Xewkija', 'Gozo Xewkija'],
            ['Gozo - Xewkija', 'Xewkija'],
            ['Gozo - Xlendi', 'Gozo Xlendi'],
            ['Gozo - Xlendi', 'Xlendi'],
            ['Gozo - Zebbug', 'Gozo Iz-Zebbug'],
            ['Gozo - Zebbug', 'Gozo Zebbug'],
            ['Gozo - Zebbug', 'Hal Saghtrija'],
            ['Gozo - Zebbug', 'Zebbug (Gozo)'],
            ['Iklin', 'L-Iklin'],
            ['Iklin', 'L\'Iklin'],
            ['Kalkara', 'Kalkara, Shoreline'],
            ['Kalkara', 'Kalkara, Smart City'],
            ['Kalkara', 'Smart City'],
            ['Kalkara', 'The Shoreline at Smart City'],
            ['Kalkara', 'The Shoreline'],
            ['Luqa', 'Hal Farrug'],
            ['Manikata', 'Ghajn Tuffieha'],
            ['Marsaskala', 'M\'Scala'],
            ['Marsaskala', 'Marsascala'],
            ['Marsaskala', 'Marsascala, Ta\' Monita Residence'],
            ['Marsaskala', 'Ta Monita Residence'],
            ['Marsaskala', 'Ta Monita'],
            ['Marsaskala', 'Ta’ Monita Residence M\'Skala'],
            ['Marsaxlokk', 'Dellimara'],
            ['Marsaxlokk', 'M\'Xlokk'],
            ['Mellieha', 'Ghadira'],
            ['Mellieha', 'Mellieha, Ghadira'],
            ['Mellieha', 'Mellieha, Santa Maria Estate'],
            ['Mellieha', 'Mellieha, Tas-Sellum'],
            ['Mellieha', 'Santa Maria Estate Mellieha'],
            ['Mellieha', 'Santa Maria Estate'],
            ['Mellieha', 'Selmun'],
            ['Mellieha', 'Southridge'],
            ['Mellieha', 'Tas Sellum'],
            ['Mgarr', 'Bingemma'],
            ['Mgarr', 'Zebbiegh'],
            ['Mqabba', 'Imqabba'],
            ['Msida', 'Msida University Heights'],
            ['Mtarfa', 'Imtarfa'],
            ['Naxxar', 'Birguma'],
            ['Naxxar', 'San Pawl Tat-Targa Naxxar'],
            ['Naxxar', 'San Pawl Tat-Targa'],
            ['Naxxar', 'San Pawl tat Targa'],
            ['Naxxar', 'San Pawl tat-Targa'],
            ['Naxxar', 'The Village'],
            ['Paola', 'Il-Kortin'],
            ['Paola', 'Paola Rahal Gdid'],
            ['Pembroke', 'St Andrew\'s'],
            ['Pembroke', 'St Andrews'],
            ['Pieta', 'G\'Mangia'],
            ['Pieta', 'Guardamangia'],
            ['Pieta', 'Gwardamanga'],
            ['Pieta', 'Gwardamangia'],
            ['Qormi', 'Handaq'],
            ['Rabat', 'Mtahleb'],
            ['Rabat', 'Rabat, Tal-Virtu'],
            ['Saint Julian\'s', 'Mercury Towers'],
            ['Saint Julian\'s', 'Pender Gardens St Julians'],
            ['Saint Julian\'s', 'Pender Gardens'],
            ['Saint Julian\'s', 'Portomaso Laguna'],
            ['Saint Julian\'s', 'Portomaso'],
            ['Saint Julian\'s', 'Sliema, Fort Cambridge'],
            ['Saint Julian\'s', 'Sliema, Tigne Point'],
            ['Saint Julian\'s', 'Sliema, Tigne'],
            ['Saint Julian\'s', 'St Julian\'S San Giljan'],
            ['Saint Julian\'s', 'St Julian\'s'],
            ['Saint Julian\'s', 'St Julians'],
            ['Saint Julian\'s', 'St Julians, Mercury House'],
            ['Saint Julian\'s', 'St Julians, Pender Gardens'],
            ['Saint Julian\'s', 'St Julians, St George\'S Park'],
            ['Saint Julian\'s', 'St Julians, The Gardens'],
            ['Saint Julian\'s', 'St. Julians'],
            ['Saint Julian\'s', 'St. Julians, Paceville'],
            ['Saint Julian\'s', 'St. Julians, Portomaso'],
            ['Saint Julian\'s', 'St. Julians, Ta\' Giorni'],
            ['Saint Julian\'s', 'St.Julians'],
            ['Saint Julian\'s', 'Ta Giorni'],
            ['Saint Julian\'s', 'Ta\' Giorni St Julians'],
            ['Saint Julian\'s', 'Ta\' Giorni'],
            ['Saint Julian\'s', 'The Gardens'],
            ['Saint Julian\'s', 'Tigne'],
            ['Saint Paul\'s Bay', 'Pender Place'],
            ['Saint Paul\'s Bay', 'Pwales'],
            ['Saint Paul\'s Bay', 'St Paul\'S Bay San Pawl Il-Bahar'],
            ['Saint Paul\'s Bay', 'St Paul\'s Bay'],
            ['Saint Paul\'s Bay', 'St Pauls Bay'],
            ['Saint Paul\'s Bay', 'St. Paul\'s Bay'],
            ['Saint Paul\'s Bay', 'St. Pauls Bay'],
            ['Saint Paul\'s Bay', 'St.Pauls Bay'],
            ['San Gwann', 'Mensija San Gwann'],
            ['San Gwann', 'Mensija'],
            ['San Gwann', 'Monterosa Gardens'],
            ['San Gwann', 'Ta\' Zwejt'],
            ['Santa Lucija', 'Santa Lucia'],
            ['Santa Venera', 'St.Venera'],
            ['Senglea', 'Isla'],
            ['Senglea', 'Senglea (L-Isla)'],
            ['Senglea', 'Senglea Isla'],
            ['Siggiewi', 'Buskett'],
            ['Sliema', 'Fort Cambridge'],
            ['Sliema', 'Tigne Point'],
            ['Swatar', 'Swatar Birkirkara'],
            ['Swieqi', 'High Ridge'],
            ['Swieqi', 'Ibrag'],
            ['Swieqi', 'Ibrag, High Ridge'],
            ['Swieqi', 'Ibrag, Victoria Gardens'],
            ['Swieqi', 'Ibragg'],
            ['Swieqi', 'Madliena Village'],
            ['Swieqi', 'Madliena, Madliena Village'],
            ['Swieqi', 'Swieqi, St Andrews'],
            ['Swieqi', 'Ta\' l-Ibragg'],
            ['Swieqi', 'Ta\' l-ibragg'],
            ['Swieqi', 'Ta\'L-ibrag'],
            ['Swieqi', 'Tal-Ibrag'],
            ['Swieqi', 'Victoria Gardens'],
            ['Ta\' Xbiex', 'Ta\'Xbiex'],
            ['Zebbug', 'Iz-Zebbug'],
            ['Zejtun', 'Bir id-deheb'],
            ['Zurrieq', 'Zurrieq Bubaqra'],
        ]

        return pd.DataFrame(data, columns=['Standard', 'Variant'])

    @staticmethod
    def imply_province() -> pd.DataFrame:
        data = [
            ['Central', 'Attard', 35.8905, 14.4199],
            ['Central', 'Balzan', 35.8957, 14.4534],
            ['Central', 'Birkirkara', 35.8955, 14.4665],
            ['Central', 'Blata Il-Bajda', 35.8877, 14.4971],
            ['Central', 'Hamrun', 35.8861, 14.4883],
            ['Central', 'Iklin', 35.9099, 14.4578],
            ['Central', 'Lija', 35.9013, 14.4403],
            ['Central', 'Mosta', 35.9142, 14.4228],
            ['Central', 'Mriehel', 35.8929, 14.4583],
            ['Central', 'Naxxar', 35.9318, 14.4316],
            ['Central', 'Qormi', 35.8764, 14.4694],
            ['Central', 'Santa Venera', 35.8902, 14.4767],
            ['Central', 'Swatar', 35.8979, 14.4796],
            ['East', 'Bahar Ic-Caghaq', 35.9373, 14.4520],
            ['East', 'Floriana', 35.8923, 14.5029],
            ['East', 'Gharghur', 35.9221, 14.4563],
            ['East', 'Gzira', 35.9059, 14.4953],
            ['East', 'Kappara', 35.9078, 14.4854],
            ['East', 'Madliena', 35.9366, 14.4731],
            ['East', 'Maghtab', 35.9425, 14.4418],
            ['East', 'Msida', 35.8956, 14.4869],
            ['East', 'Paceville', 35.9231, 14.4913],
            ['East', 'Pembroke', 35.9291, 14.4752],
            ['East', 'Pieta', 35.8934, 14.4942],
            ['East', 'Saint Julian\'s', 35.9181, 14.4883],
            ['East', 'San Gwann', 35.9077, 14.4752],
            ['East', 'Sliema', 35.9110, 14.5029],
            ['East', 'Swieqi', 35.9191, 14.4694],
            ['East', 'Ta\' Xbiex', 35.8991, 14.4964],
            ['East', 'Valletta', 35.8989, 14.5146],
            ['Gozo', 'Gozo - Citadel', 36.0465, 14.2398],
            ['Gozo', 'Gozo - Fontana', 36.0369, 14.2352],
            ['Gozo', 'Gozo - Ghajnsielem', 36.0248, 14.2803],
            ['Gozo', 'Gozo - Gharb', 36.0689, 14.2018],
            ['Gozo', 'Gozo - Ghasri', 36.0668,14.2192 ],
            ['Gozo', 'Gozo - Kercem', 36.0448, 14.2251],
            ['Gozo', 'Gozo - Marsalforn', 36.0717, 14.2556],
            ['Gozo', 'Gozo - Mdina', 36.0462, 14.2394],
            ['Gozo', 'Gozo - Mgarr', 36.0246, 14.2985],
            ['Gozo', 'Gozo - Munxar', 36.0288, 14.2251],
            ['Gozo', 'Gozo - Nadur', 36.0447, 14.2919],
            ['Gozo', 'Gozo - Qala', 36.0389, 14.3181],
            ['Gozo', 'Gozo - San Lawrenz', 36.0483, 14.1960],
            ['Gozo', 'Gozo - Sannat', 36.0193, 14.2599],
            ['Gozo', 'Gozo - Victoria', 36.0427, 14.2425],
            ['Gozo', 'Gozo - Xaghra', 36.0508, 14.2675],
            ['Gozo', 'Gozo - Xewkija', 36.0299, 14.2599],
            ['Gozo', 'Gozo - Xlendi', 36.0313, 14.2174],
            ['Gozo', 'Gozo - Zebbug', 36.0716, 14.2454],
            ['North', 'Bidnija', 35.9277, 14.3996],
            ['North', 'Bugibba', 35.9484, 14.4110],
            ['North', 'Burmarrad', 35.9350, 14.4156],
            ['North', 'Manikata', 35.9312, 14.3479],
            ['North', 'Mellieha', 35.9524, 14.3501],
            ['North', 'Mgarr', 35.9189, 14.3617],
            ['North', 'Qawra', 35.9542, 14.4197],
            ['North', 'Saint Paul\'s Bay', 35.9360, 14.3967],
            ['North', 'Salina', 35.9443, 14.4272],
            ['North', 'Wardija', 35.9390, 14.3937],
            ['North', 'Xemxija', 35.9506, 14.3802],
            ['South', 'Birgu', 35.8879, 14.5226],
            ['South', 'Birzebbuga', 35.8136, 14.5247],
            ['South', 'Cospicua', 35.8807, 14.5218],
            ['South', 'Fgura', 35.8738, 14.5233],
            ['South', 'Ghaxaq', 35.8440, 14.5160],
            ['South', 'Gudja', 35.8470, 14.5029],
            ['South', 'Hal Far', 35.8181, 14.5102],
            ['South', 'Kalkara', 35.8914, 14.5320],
            ['South', 'Kirkop', 35.8438, 14.4854],
            ['South', 'Luqa', 35.8583, 14.4869],
            ['South', 'Marsa', 35.8736, 14.4927],
            ['South', 'Marsaskala', 35.8604, 14.5568],
            ['South', 'Marsaxlokk', 35.8412, 14.5393],
            ['South', 'Mqabba', 35.8444, 14.4694],
            ['South', 'Paola', 35.8821, 14.5102],
            ['South', 'Qrendi', 35.8328, 14.4549],
            ['South', 'Safi', 35.8362, 14.4927],
            ['South', 'Santa Lucija', 35.8561, 14.5044],
            ['South', 'Senglea', 35.8873, 14.5167],
            ['South', 'Tarxien', 35.8673, 14.5116],
            ['South', 'Xghajra', 35.8868, 14.5472],
            ['South', 'Zabbar', 35.8725, 14.5451],
            ['South', 'Zejtun', 35.8549, 14.5364],
            ['South', 'Zurrieq', 35.8216, 14.4811],
            ['West', 'Bahrija', 35.8952, 14.3486],
            ['West', 'Dingli', 35.8627, 14.3850],
            ['West', 'Mdina', 35.8881, 14.4068],
            ['West', 'Mtarfa', 35.8895, 14.3952],
            ['West', 'Rabat', 35.8855, 14.3734],
            ['West', 'Siggiewi', 35.8464, 14.4316],
            ['West', 'Zebbug', 35.8765, 14.4391]
        ]

        return pd.DataFrame(data, columns=['Province', 'Town', 'Latitude', 'Longitude'])
